### ISSUE TITLE
Compatibility with SmartMoving (and Render Player API)

### ISSUE THREAD

**Issue by vpontin** [zlainsama/SkinPort#1]
Hi!
I'm experiencing a crash trying to use SkinPort with SmartMoving (and Render Player API):

https://gist.github.com/vpontin/1a0c266b1ee0f3620a86

Is possible to fix it?

**Comment by zlainsama** [comment]
Hi!
I will try, at least the crash is definitely possible to fix.

**Comment by vpontin** [comment]
Thanks!

**Comment by zlainsama** [comment]
A new version, 1.7.10-v4, has been released now.
It should be compatible with SmartMoving and RenderPlayerAPI.
I only tested in single player. But it should be same in multiplayer.
Release on curse will have a little delay as they need to be reviewed by curse first.
If it has any remain problem, you can reopen the issue to inform me.
