### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by runescapejon** [zlainsama/SkinPort#11]
like the title said one of my player had send me a crash report and looks like it's coming from this mod here is the crash report http://pastebin.com/93wg5XBt

**Comment by zlainsama** [comment]
does this happens consistently? like every time he sees other players on his screen?
if not, this is just a rare case which i can't do anything about (it happened to me before with completely different modpacks, and i have no clue).

**Comment by runescapejon** [comment]
i'm not sure happen random. but if there more information  that players can give me i will post it here thanks
