### ISSUE TITLE
Skinport compatibility with ArmorWorkShop mod 

### ISSUE THREAD

**Issue by runescapejon** [zlainsama/SkinPort#14]
Hello,

so really there only one annoying issue
when you have SkinPort-1.7.10-v8c and Armourers-Workshop-1.7.10-0.47.1
and go ingame look at your inventory this spam in clientside 
https://pastebin.com/myHB7Z3m
it's really annnoying when your trying to debug something

**Comment by zlainsama** [comment]
I'm sorry about this.
I just checked minecraft/forge code to see if i can provide image files to resourcemanager, and there's nothing i can do other than do some more hacky stuff like replacing certain instances. (maybe i'm blind)
You could ask Armourers-Workshop to not complain about FileNotFoundException.
Or, if you insist, i can make a version do some more hacky stuff later. (this mod already does some hacky stuff using coremod)

**Comment by runescapejon** [comment]
Sure I'll ask

**Comment by runescapejon** [comment]
okay he just message back he give a fix for the issue
Armorworkshop config and set texturePainting = 2 to disable it he said should fix the issue he also label the 
issue Compatibility
