### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by felipeleite5w** [zlainsama/SkinPort#17]
So, I have a 1.7.10 server in offline mode and I want to know if client side and server side use that mod everybody will see theirs ''new skin''

**Comment by felipeleite5w** [comment]
Players will be able too choose their skins?

**Comment by zlainsama** [comment]
If they have their new skins in their minecraft account, yes.
Otherwise, you will need a custom skin server that supports uploading skins by users.

**Comment by felipeleite5w** [comment]
ok but cracked clients, will be able so theirs new skin?

**Comment by zlainsama** [comment]
Yes, the mod does not check accounts.
You will need a custom skin server that supports uploading skins from your users.
I'm not gonna help you in setting up such custom skin server.

If you are enjoying Minecraft, please consider buying it.

**Comment by felipeleite5w** [comment]
I already bought minecraft a lot time ago !

**Comment by felipeleite5w** [comment]
No problem I found a better mod

**Comment by zlainsama** [comment]
okay
