### ISSUE TITLE
Trouble with Minecraft Comes Alive

### ISSUE THREAD

**Issue by vpontin** [zlainsama/SkinPort#2]
Hi again!

Now i having a strange issue with Minecraft Comes Alive.

Everytime i enter in a world with MCA villagers, my skin wont show; switching to a non-MCA world wont fix; And when i load first a world without MCA villagers, my skin show, but when i exit and enter a MCA filled world, the skin disappears.

No related (or significant) line appears on my logs.

Is it fixable?

**Comment by zlainsama** [comment]
Hi!
Which version is it? I will try it in my end to find out what cause that.

**Comment by zlainsama** [comment]
I tested it with only MCA-1.7.10-5.0.7.2-universal and RadixCore-1.7.10-2.0.3-universal installed.
It worked perfectly.
Maybe it's just the skin server down occasionally?

**Comment by vpontin** [comment]
After updating RadixCore, the skin funcionality seems to stop at all here.
But i partly solved my problem placing a copy of my skin file in cachedimages.
How i don't like to play on public SMP, for me its end here.
If @zlainsama wants, you can close.

**Comment by vpontin** [comment]
Well, i think i have news: in fact seems like i having 2 issues: This related in the OP, plus switching worlds in singleplayer. Everytime i close a world and open another, the skin disappears. Dont ocour normally without this mod, so i think it can be something related to world switching and this mod.

About the first issue, tomorrow i will remove MCA and radixcore to test. Can be something still with SmartMoving, idk

If needed, i can open another issue, but both can be related.

**Comment by zlainsama** [comment]
I use a cache to store skin, if the skin is not being used(rendered) in 15 seconds, it will be invalidated and another one will be issued to start fetching from mojang or other skin provider services.
This mechanism will allow you to change your skin without restarting your game. As long as you return to your world in 15 seconds, the skin should be still valid to use. (vanilla is also using this type of mechanism but with additional skin file cache located in assets folder)

**Comment by zlainsama** [comment]
I have three skin provider included in the mod.
One for Mojang, it will fetch skin using Mojang skin server.
One for Crafatar, it will fetch skin using Crafatar skin server, which will cache your skin from Mojang for you when Mojang skin server is down.
Last one is user managed skin storage, it basically look for skin files in cachedImages, if found it will provide it to the Game for it to render.

Crafatar and user managed skin storage will be overrided when skin fetched from Mojang server is ready.

**Comment by zlainsama** [comment]
I don't think MCA have anything to do with player model or player skin. It might be problem with other mods you installed.
