### ISSUE TITLE
suggestion for easy setup

### ISSUE THREAD

**Issue by k1r0s** [zlainsama/SkinPort#20]
Is there any problem for allowing this mod to download skins automatically and resolve on cachedImages?

**Comment by zlainsama** [comment]
I'm not sure what you are talking about

**Comment by k1r0s** [comment]
im suggesting that, rather than explicitly providing the PNG for some player name. Automatically resolve player skin when logged. If skin exists (appeasrs on some skin repository) download the PNG and store it con cachedImages/skins.. etc

**Comment by zlainsama** [comment]
It is already doing that except, it does not store them, it keeps them in memory until they are no longer used in game for 15 seconds.
Providing PNG for players is really just a way for offline situations like 1) no internet access; 2) internet access is really unstable; 3) your ISP is acting funky.
By default, it uses Mojang's and Crafatar's skin server, only a real account with skin access to Mojang's service will be able to have skin in this way.
You can however, use the custom skin server option to make it uses a skin server you setup.

**Comment by k1r0s** [comment]
fair enough
