### ISSUE TITLE
A question about HD skin / 关于高清皮肤的问题

### ISSUE THREAD

**Issue by tnqzh123** [zlainsama/SkinPort#22]
（开发者也是国人的话正文我就用中文写了，如有不便，深感抱歉）

我看到了 SkinPort 的介绍中写着“Alex/Slim 模型只会在 (55,20) 完全透明的情况下适用”，对于高清皮肤来说，乘上对应比例的话，是需要哪个坐标的像素透明，还是某一范围内的像素全透明呢？

比如，我有一份 128\*128 的 Slim 模型的高清皮肤，是需要 (109,41) 这个像素透明，还是需要 (109,41) 到 (110,42) 范围内的 4 个像素全透明呢？

**Comment by zlainsama** [comment]
https://github.com/zlainsama/SkinPort/blob/master/src/main/java/lain/mods/skins/impl/SkinData.java#L31-L32

是需要 (110, 40) 这单个像素透明
