### ISSUE TITLE
Support for More Player Models

### ISSUE THREAD

**Issue by Dakedres** [zlainsama/SkinPort#23]
I'd really like to see added support for the [More Player Models](https://www.curseforge.com/minecraft/mc-mods/more-player-models) mod, by Noppes. It adds the ability to further modify the player model, and I'd really love to see SkinPort add support, as it'd allow the same amount of skin customization possible in modded 1.8+

**Comment by zlainsama** [comment]
I think it will involve too much effort for this to happen.
I will look into this when i have time, no guarantee though.

**Comment by Dakedres** [comment]
Thanks

**Comment by zlainsama** [comment]
Please test this: https://github.com/zlainsama/SkinPort/releases/tag/1.7.10-v10

**Comment by Dakedres** [comment]
My bad, I'm sorry I haven't been on GitHub recently. I'll try that, thank you.
