### ISSUE TITLE
Optifine Cape

### ISSUE THREAD

**Issue by COMFIRMED** [zlainsama/SkinPort#24]
I Dont See My Optifine Cape Pls check this when i change the version of the mod to 2016 version my old skin is back (alex skin) I got steve skin And I dont see My Cape

**Comment by zlainsama** [comment]
I will try to see if i can get this fixed when i have time, no guarantee though.

**Comment by zlainsama** [comment]
Please test this: https://github.com/zlainsama/SkinPort/releases/tag/1.7.10-v10
