### ISSUE TITLE
[feature request] use placeholders format instead of the hostCustomServer format in skinport.cfg

### ISSUE THREAD

**Issue by jinzhijie** [zlainsama/SkinPort#25]
## feature request
use placeholders format instead of the `hostCustomServer` format in `skinport.cfg`

在 `skinport.cfg` 中使用占位符替换 `hostCustomServer` 的格式

*p.s.  I'm not very good at English. If you can understand Simplified Chinese, please refer to it. The English texts were translated by Google.*

BTW, 开发者应该是国人吧？

## currently / 现状
The stitching method of the URL of hostCustomServer is defined in the code. Just like: `/skins/(uuid|username) and /capes/(uuid|username) will be queried for respective resources`

However, **not all of the custom servers support this approach.** Such as [Blessing Skin Server](https://github.com/bs-community/blessing-skin-server)

目前，hostCustomServer 的 URL 的拼接方式是在代码中写死的。然而，并不是所有的自定义服务器都支持这种方式。例如：[Blessing Skin Server](https://github.com/bs-community/blessing-skin-server)

## I hope / 预期
e.g. 
- `S:customSkinUrl=https://example.com/skins/%name%.png`
- `S:customCapeUrl=https://example.com/capes/%uuid%`

---

If you have any comments, you can make them below.
如果你有任何意见，请在下方提出 :D

**Comment by zlainsama** [comment]
可以是可以，不过得过段时间，请耐心等待。

**Comment by jinzhijie** [comment]
> 可以是可以，不过得过段时间，请耐心等待。

太感谢了！

**Comment by jinzhijie** [comment]
https://github.com/zlainsama/SkinPort/issues/25

**Comment by zlainsama** [comment]
请试试这个: https://github.com/zlainsama/SkinPort/releases/tag/1.7.10-v10

**Comment by jinzhijie** [comment]
测试通过
