### ISSUE TITLE
1.7.10 skin BUG 

### ISSUE THREAD

**Issue by zxterProxy** [zlainsama/SkinPort#29]
I really love 1.7.10 and I am happy that sometimes they make cool backports.

I was happy when I saw this mod. But it's a pity it gives such an effect.

What should I do about it? The mod is both on the server and on the client. + the site has a skin with 2 layers *
![Screenshot_2](https://user-images.githubusercontent.com/47256412/108621577-82716600-7444-11eb-870e-661b058735a1.png)
![crusaderfootman8572121](https://user-images.githubusercontent.com/47256412/108621578-856c5680-7444-11eb-9ba3-f76d2521154f.png)

**Comment by zxterProxy** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/47256412/108621582-8a310a80-7444-11eb-852d-2fa93924f2e7.png)

**Comment by zlainsama** [comment]
I just tested with only this mod installed, it worked fine for me.
You are probably experiencing incompatibilities with other mods.
![image](https://user-images.githubusercontent.com/3251859/108630325-1bcd6600-749f-11eb-9a42-52c6482f3779.png)

**Comment by zxterProxy** [comment]
I had one optifine and your mod

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108630738-5cb18480-7477-11eb-9754-f46a1ba1fc71.png)
![image](https://user-images.githubusercontent.com/47256412/108630745-66d38300-7477-11eb-9235-41d185de446f.png)
[log.txt](https://github.com/zlainsama/SkinPort/files/6018020/log.txt)

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108630770-8b2f5f80-7477-11eb-9b13-fc0bc6d046d3.png)

**Comment by zxterProxy** [comment]
I'm asking you very much... Please fix this. My server just needs this mod. He's too cool *
Even the alex model as a 2 layer is not important

**Comment by zlainsama** [comment]
... with optifine, in my end, it still worked fine ...

![image](https://user-images.githubusercontent.com/3251859/108634202-7bce0780-74b3-11eb-9b7e-18b4348e9f1b.png)

I can't fix it if I don't know how to reproduce it ...

**Comment by zlainsama** [comment]
I'm using same Forge, Optifine, SkinPort as yours.
There might be a problem with your launcher.

**Comment by zlainsama** [comment]
Also, you should probably edit that comment and delete the link to that log file, it contained information about your email address.

**Comment by zxterProxy** [comment]
Now I will try to create a clean client with forge on the official launcher

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108635355-161c5400-7490-11eb-9fcd-28630d34b546.png)
WTF how ????


The whole point is to use the official launcher ?
It turns out there is no sense to put a mod on a custom launcher by type
https://github.com/GravitLauncher/VueWiki

Can you guess why this is happening ?

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108635511-c8541b80-7490-11eb-9e4c-a8ea0c5eaaab.png)
I installed optifine and this happened

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108635549-fd606e00-7490-11eb-95d4-ebb77ce88445.png)
Removed the optifine

**Comment by zlainsama** [comment]
Hmm, what steps are you taking to install Optifine?
Just put it in the mods folder should work fine if the version of Forge is supported.

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108635663-94c5c100-7491-11eb-81ee-5ce2b877fa00.png)
That's what I do )

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108635681-ad35db80-7491-11eb-8f81-7b583e281635.png)
I restart the client and it then issues a bug that does not issue....

**Comment by zlainsama** [comment]
So... it no long happens?

**Comment by zxterProxy** [comment]
If you use third-party launchers. Then you can get this bug with 100% probability

**Comment by zxterProxy** [comment]
Happens

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108635783-5b418580-7492-11eb-95ac-2ea411673d77.png)
that is this bug then there is no it

**Comment by zxterProxy** [comment]
In version 8c of your mod, there is no this bug, but the mod is not put on the server and people do not see the second layer from each other. This trash starts with version v9a

**Comment by zlainsama** [comment]
Hmm, I might know a potential cause, I will compile a modified version for you to test.

**Comment by zxterProxy** [comment]
I used
classic minecraft launcher
download the launcher
ftb launcher
tlauncher (this is a popular launcher in Russia)
and its own launcher based on graphite launcher...

This error is everywhere. The only thing in the classic launcher is that it happens every other time

**Comment by zxterProxy** [comment]
I fucking love you !
I've been sitting here all day like a moron going over the versions )
This is a matter of honor XD

**Comment by zlainsama** [comment]
[Deleted]

Can you try this to see if it fixes the issue?

**Comment by zxterProxy** [comment]
I'll check it out now )

**Comment by zxterProxy** [comment]
![image](https://user-images.githubusercontent.com/47256412/108636597-5f23d680-7497-11eb-8699-4616c133914b.png)
So )
It's already working )
Now I'll check it on my launcher !)

**Comment by zxterProxy** [comment]
Whoa! I think everything works!
Thank you very much!
If anything, I'll keep you posted!

Do not throw away the legacy and you will always be remembered )
Many more people love the unique mods for this 1.7 )
I think it's too early to keep it. Recently by the way awesome backports on nezer came out )

**Comment by zlainsama** [comment]
Okay, I'll remove the test version, and do a proper release. Thanks for testing.

**Comment by zxterProxy** [comment]
I should be thanking you !
Thank you for the mod!
Health to you bro !)
