### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tartilla-TAIGO** [zlainsama/SkinPort#38]
Hi. For some reason, the mod does not work when starting the game, although everything works fine through another launcher. What could be the problem?  Skin on server - TaigoStudio, https://dpc.launcher.apecraft.land/services/skins/download/TaigoStudio
[skinport.cfg.txt](https://github.com/zlainsama/SkinPort/files/11833652/skinport.cfg.txt)

**Comment by Tartilla-TAIGO** [comment]
The problem is observed when using an SSL certificate on a domain. If you use an http connection, then the problem is not observed

**Comment by zlainsama** [comment]
I'm not sure the cause too.
You could check to see if the other launcher is using a different java implementation from yours, some old java implementations have issues connecting https.
Also, you should remove that latest.log as it contains password in plain text.

**Comment by Tartilla-TAIGO** [comment]
Yes, this launcher uses a different version of Java, which is different from the one that is installed on the computer. The launcher uses Java 1.8.0_51. Okay, I'll delete the log with the password. Thank you for seeing this

**Comment by Tartilla-TAIGO** [comment]
Another launcher (where the mod works with SSL), in turn, uses the 1.8.0_151 version of Java. Very strange, because Mojang recommends using Java 1.8.0_51 (https://launchermeta.mojang.com/mc/launcher.json)

**Comment by zlainsama** [comment]
I think the old java implementations only have problems connecting those sites with Let's Encrypt certificates (which your skin server is one of them), and vanilla Minecraft does not connect to any of those, so Mojang doesn't need to update.

**Comment by Tartilla-TAIGO** [comment]
Okay, thank you
