### ISSUE TITLE
Witchery Werewolf render issue

### ISSUE THREAD

**Issue by 63502** [zlainsama/SkinPort#4]
I don't know if this is related to #3 , but when I change to wolf or wolfman form with this mod installed, my 1.8 player skin renders on my players hand in first person instead of the corresponding wolf or wolfman texture. It does not affect the third person view, or any other features related to werewolf.

**Comment by zlainsama** [comment]
I am aware of this when I was playing with witchery myself, it kind bothered me a little but I got used to it.
I could temporarily disable the mod while you are in wolf or wolfman form. But same as MPM, witchery is also not an open-sourced mod. I can't do anything to witchery mod without prior written permission of the Owner of the witchery mod. I sent an request to the witchery author about exposing some API for addon mods before, but I have not got a reply yet.

**Comment by zlainsama** [comment]
I will look into forge code to see if I can do anything to fix this.

**Comment by 63502** [comment]
ok, thanks.

**Comment by zlainsama** [comment]
This issue should get partially fixed in v6. Sorry, but a complete fix will require me to change a lot more code.

**Comment by 63502** [comment]
I just tested this update, I can confirm the partial fix. The texture rendering  is not entirely correct, but it has the correct colors and no longer superimposes 1.8 player skins onto the witchery wolf and wolfman hands.

Thanks! :D

**Comment by zlainsama** [comment]
:)
