### ISSUE TITLE
Increasing resolution

### ISSUE THREAD

**Issue by Volrajh** [zlainsama/SkinPort#6]
Do you think it is possible to change your mod for skins in 64x128 (symmetric) or 128x128 (asymmetric)?
Thank you !

Vald

**Comment by zlainsama** [comment]
Yes, it is possible.

**Comment by zlainsama** [comment]
But since this mod will only be available for 1.7.10 and mojang does not support high res skins on their server, you need to do the modification on your own and setup a skin server for that purpose.

**Comment by Volrajh** [comment]
Is it complicated? This requires what level of programming?

**Comment by zlainsama** [comment]
Changing some parameters should be enough.

**Comment by Volrajh** [comment]
I changed my launcher to use my skin server.
Can you give me directions on what to change in your mod?

**Comment by zlainsama** [comment]
If my memory serves me correctly, changing some parameters in these files should get the job done.
/src/main/java/lain/mods/skinport/SkinData.java
/src/main/java/lain/mods/skinport/SkinPortModelPlayer.java
/src/main/java/lain/mods/skinport/compat/SkinPortModelPlayer_RPA.java

**Comment by Volrajh** [comment]
Thank you ! I'll see it soon. I might come back for more questions!

**Comment by zlainsama** [comment]
Oh, and this one too.
/src/main/java/lain/mods/skinport/LegacyConversion.java

**Comment by zlainsama** [comment]
v9a has HD skins support now.
